# Generated by Django 6.0.4 on 2026-06-21 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_verified',
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
